spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  mvc:
    path-match:
      matching-strategy: ant_path_matcher

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

application:
  kakao-api:
    uri: https://dapi.kakao.com/v2/search/blog
    key: 97af1dc06061a48fcbe42a1c78e0f671
  naver-api:
    uri: https://openapi.naver.com/v1/search/blog.json
    id: tyOBl5W1eWuM1zIMGBI9
    secret: chMQo0aPTB